services:
    crawler-vk:
        image: nymless/crawler-vk
        build:
            context: ./crawler-vk
            dockerfile: Dockerfile
        env_file: ./.env
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 127.0.0.1:8000:8000
        restart: always
        environment:
            - CRAWLER_DATA_DIR=/app/data
        volumes:
            - ./data:/app/data
    front-next:
        image: nymless/front-next
        build:
            context: ./front-next
            dockerfile: Dockerfile.compose
            args:
                DB_NAME: ${DB_NAME}
                DB_USER: ${DB_USER}
                DB_PASSWORD: ${DB_PASSWORD}
                DB_PORT: ${DB_PORT}
                DB_HOST: ${DB_HOST}
                JWT_SECRET: ${JWT_SECRET}
                CRAWLER_URL: http://crawler-vk:8000
        env_file: ./.env
        environment:
            CRAWLER_URL: http://crawler-vk:8000
        extra_hosts:
            - host.docker.internal:host-gateway
        ports:
            - 127.0.0.1:3000:3000
        restart: always

networks:
  crawler-net:
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
