services:
    crawler-vk:
        build: ./crawler-vk
        environment:
            DATABASE_URL: ${DB_URL}
        ports:
            - "8000:8000"
        restart: always

    backend:
        build: ./backend
        environment:
            DATABASE_URL: ${DB_URL}
        ports:
            - "3000:3000"
        restart: always
